### ISSUE TITLE
Add some basic infrastructure 

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/ConfigJSR#1]
add readme doc

**Comment by hendrikebbers** [comment]
[] Travis Build (or do we want to use any other build service?)
[] Publishing documentation to github pages

**Comment by ottlinger** [comment]
As Tamaya already contains a sandbox implementation of this API it would be great if SNAPSHOTs were deployed to a public Maven repository in order to be available for downstream projects.

Is there an infra for that at Eclipse or can you just upload to Maven Central?

Thanks

**Comment by atsticks** [comment]
+1 
We also have a Tamaya branch (configjsr) that uses the JSRs API as a first class citizen, so a full JSR implementation. Also the extensions done so far in Tamaya work successfully, currently the sandbox only is work in progress.

**Comment by ottlinger** [comment]
At the moment we integrated the API via jitpack but hope to be able to switch to a stable JAR - 
just fyi

**Comment by ottlinger** [comment]
@struberg why did you close the ticket? Is there a publicly available first release? or is one planned?

**Comment by struberg** [comment]
hmm basic infrastructure is set up, isn't? 
What's missing still?

**Comment by ottlinger** [comment]
@struberg how can we reference the API SNAPSHOT in different implementations if it's not available via maven central? That's IMHO part of a basic infrastructure

**Comment by struberg** [comment]
oh sorry, you are totally right. Just glimpsed over the list of open issues and try to close resolved parts. Seems I was a bit too quick with this one...
