### ISSUE TITLE
Remove asList() asSet(), as() from ConfigAccessor

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/ConfigJSR#106]
In our hangout, we discussed the methods in ConfigAccessor. We agreed the following methods 
asList
asSet
as() 
as it introduced risks to cast to a different type, which cause problems.

**Comment by brenopessoa** [comment]
Hello , I tried  to solve this issue and during refactoring the tests,  I  did a suggestion a overload of method   

ConfigAccessor<String> access(String propertyName);

with 

<T> ConfigAccessor<T> access(String propertyName,Class<T> propertyType);

Please , verify if worth it.
Thanks.

**Comment by Emily-Jiang** [comment]
@brenopessoa thanks for doing the PRs! We discuss the issues in our config jsr calls and refine the APIs. Please don't simply look at the issues and spend time to do the PR, as we have not agreed on the resolution as yet.

**Comment by brenopessoa** [comment]
Hi @Emily-Jiang  thank's for the feedback. 
So it would be good to mark the issues "ready" to working-on.
