### ISSUE TITLE
Configuration Interception

### ISSUE THREAD

**Issue by atsticks** [eclipse/ConfigJSR#11]
One additional feature that Tamaya provides is the possibility to intercept the evaluation of configuration. The main mechanism here is the [`PropertyFilter`](https://github.com/apache/incubator-tamaya/blob/master/code/api/src/main/java/org/apache/tamaya/spi/PropertyFilter.java), which can apply changes to the _raw_ String value, before applying any converter logic. This mechanism has shown to be very useful for security based filtering and implementing placeholder/resolver logic. The question is if that should be a vendor specific feature, or it should be part of the official API.

**Comment by struberg** [comment]
In MicroProfile Config we had this initially. It's basically the DeltaSpike ConfigFilter. 
In MP we intentionally removed this after some feedback from Viktor Klang https://github.com/eclipse/microprofile-config/pull/1

**Comment by atsticks** [comment]
I cant find the exact discussion on filters. must look at it on a pc ...

Am 31.10.2017 14:25 schrieb "Mark Struberg" <notifications@github.com>:

In MicroProfile Config we had this initially. It's basically the DeltaSpike
ConfigFilter.
In MP we intentionally removed this after some feedback from Viktor Klang
eclipse/microprofile-config#1
<https://github.com/eclipse/microprofile-config/pull/1>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/eclipse/ConfigJSR/issues/11#issuecomment-340761021>,
or mute
the thread

**Comment by Emily-Jiang** [comment]
I cannot recall the ConfigFilter discussion.

**Comment by struberg** [comment]
I vividly remember that we had the discussion. It was between Ondro, Viktor Klang and me mostly. 

You can still find the contribution notice in our code:
https://github.com/eclipse/ConfigJSR/blob/master/api/src/main/java/javax/config/ConfigProvider.java#L27

**Comment by Emily-Jiang** [comment]
Is this used for filtering out some properties? Can this be achieved by the implementation of ConfigSource? Basically read the properties and filter some out based on some criteria.

**Comment by atsticks** [comment]
There are several use cases:
- Filtering out properties
- Implement property value (tbd: key) conversion as external modulke. This would allow to cover various use cases without having to add them to the basic API:
  - placeholders
  - masking
  - ACLs for config access
  - other?

In Tamaya this mechanism has proven to be very useful. The filter IMO is best applied before any conversion, so it is a simple Function<String,String>. Simple mechanism, but with many use cases.

**Comment by Emily-Jiang** [comment]
Let's close this and then reopen it at a later release if needed.
