### ISSUE TITLE
Support for 'common sense converters'

### ISSUE THREAD

**Issue by struberg** [eclipse/ConfigJSR#13]
It seems that Apache Tamaya has a feature we miss yet in MP-config and thus also in the config JSR. 
https://github.com/eclipse/microprofile-config/issues/248

It's basically about picking up implicit conversion behaviour based on some certain criteria.

* Does a constructor(String) exist for the target class?
* Does a valueOf(String) method exist?
* Does a parse(String) method exist?

I think it would be rather easy and very beneficial to add this to our spec. Wdyt?

**Comment by Emily-Jiang** [comment]
+1. Archaius supports this as well.

**Comment by jeanouii** [comment]
Yes also agree

* constructor with a String
* static method with a String
* java.beans.PropertyEditor

**Comment by atsticks** [comment]
Tamaya also supports String creation for `Enum `types, using the` valueOf(String)` method.

**Comment by Emily-Jiang** [comment]
We have two options:
1. constructor(String) -> valueOf(String) -> parse(String) easy and less problematic
2. constructor(CharSequence) ->valueOf(CharSequence) -> parse(CharSequence) 
if constructor(String), constructor(StringBuilder), constructor(StringBuffer), other implementation classes, what order should we support?

**Comment by hendrikebbers** [comment]
Discussed in the weekly: 
Idea of adding an annotation (@ConverterMethod or something) that can be used to annotate static methods in custom / own classes. This would avoid "magic methods" in custom classes.

**Comment by Emily-Jiang** [comment]
To sync up with ConfigJSR, the proposed solution is 
However, to improve the performance (as valueOf has a cache facility while the constructor does not have) and take into the new JVM class method naming scheme, I suggest we update the search sequence for the implicit converter.

    the target type {@code T} has a {@code public static T of(String)} method
    the target type {@code T} has a {@code public static T valueOf(String)} method, or
    The target type {@code T} has a public Constructor with a String parameter, or
    the target type {@code T} has a {@code public static T parse(CharSequence)} method
This should cover all useful classes and it is clear and short.
