### ISSUE TITLE
Consider project name under for RI (if any) and TCK

### ISSUE THREAD

**Issue by keilw** [eclipse/ConfigJSR#15]
At the moment modules other than the API use a package name `org.eclipse.configjsr`. That seems legitimate (it is unlikely another Eclipse project uses that name), but most other Eclipse projects used as RI for JSRs did pick a "friendly" code-name, e.g. EclipseLink, Yasson, etc. 

Could we also try to find such a code-name?

**Comment by Emily-Jiang** [comment]
yep. interesting point. We can discuss to see which code-name is more appropriate.

**Comment by struberg** [comment]
The org.eclipse.configjsr mimics the way it's done in JBatch, CDI, BeanValidation, etc.
The TCK is not the implmentation, but otoh it is also not in the javax.config package of course.

**Comment by keilw** [comment]
Yes, we also did something similar with JSR 363 except RI and TCK there share the same package domain "tec.units". So far 363 also had no "friendly" RI code-name, but we did a survey for the next release and found one.

**Comment by keilw** [comment]
There needs to be a RI, but it may depend, if it was established/used at Eclipse or EE4J, Apache or somewhere else.

**Comment by Emily-Jiang** [comment]
As long as the RI is Apache license, we will be fine. Maybe we can create a RI in Eclipse repo? Thoughts?

**Comment by keilw** [comment]
Let's discuss it today. @atsticks wanted to talk about it last week but he could not make it and other topics took more time. He said he plans to join today and as I have a headset I should also make it. I would rather avoid creating the RI directly in the JSR repo itself. TCK, that sounds possible there as it is tied to the spec, but the RI even if it is the official reference implementation better have a separate repo. JCache did, and all other JSRs I know or participate in. Other candidates could be those at Apache (Geronimo or Tamaya)

**Comment by keilw** [comment]
So what's the RI now, or will the JSR be abandoned at the JCP in which case there can be more than one "Compatible Implementation" of a Jakarta EE spec?
