### ISSUE TITLE
Discuss: allow multiple converter instances per type

### ISSUE THREAD

**Issue by atsticks** [eclipse/ConfigJSR#16]
In Tamaya a target type can have multiple converters registered. The order is defined by `@Priority `annotations and the fully qualified class name. If a converter cannot convert a value the next in order is called until a value could be converted or no more converters are available.

- Pro:  You can add additional formats for a type easily, without having to support all other formats existing as well.
- Contra: More complexity

**Comment by struberg** [comment]
Valid options. In MP-config we had this discussion as well and ended up only supporting one effective Converter per type. The one with the highest @Priority will be used.

Yes, there might be cases where a fallback handling might be useful. But it's
a.) very seldom the case
b.) Even in the case of the meed for multiple converters one could still provide an own Converter and does the fallback handling in code. Basically delegating to the other Converters in code.

With this trick we can keep the Converter logic really straight forward. But are still able to even solve complex requirements.

**Comment by Emily-Jiang** [comment]
Let's not do fallback, as it is difficult to debug. Priority is already supported anyway.

**Comment by Emily-Jiang** [comment]
@struberg and I discussed this and we agreed this should be closed. Please reopen if you think otherwise.
