### ISSUE TITLE
Add fallback property for resolving the initial ConfigProviderResolver

### ISSUE THREAD

**Issue by atsticks** [eclipse/ConfigJSR#20]
Currently the load SPI method strictly is relying on the `ServiceLoader`:

```
private static ConfigProviderResolver loadSpi(ClassLoader cl) {
        ...
        ServiceLoader<ConfigProviderResolver> sl = ServiceLoader.load(
                            ConfigProviderResolver.class, cl);
        ...
}
```

Adding a more complex service discovery mechanism is not required, but what would be a nice addition that would help in special environments is allowing a system property to define the explicit class to be loaded, instead of throwing an exception if multiple classes are registrered.
Summarizing my proposal is to add a system property `javax.config.spi.ConfigProviderResolver` to pass explicitly the class to be loaded. If not set, the default service loader functionality should be used as of now, also throwing error, when multiple implementations are registered.

**Comment by struberg** [comment]
Not needed. You can delegate through to a more complex pickup delegation mechanism anyway. That's the way it's done in multiple specs.

**Comment by atsticks** [comment]
Agreed.
