### ISSUE TITLE
define a mapping rule from config property name to environment variable

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/ConfigJSR#24]
As the name of environment variable can only use alphabets and _ , it is different to override some config properties as environment variables.

e.g.
com.acme.me="blah"

This property cannot be specified as environment variable. How about to directly translate . to _ for the corresponding environment variables. 

com.acme.me -> com_acme_me
In this way, this property can be defined or override in environment variable.

**Comment by struberg** [comment]
+1 to add it explicitly!

been there, done that 2 years ago ;) 

https://issues.apache.org/jira/browse/DELTASPIKE-1090
https://github.com/apache/deltaspike/blame/master/deltaspike/core/impl/src/main/java/org/apache/deltaspike/core/impl/config/EnvironmentPropertyConfigSource.java#L55

**Comment by kazumura** [comment]
That means you cannot use '_' as a property key.

```
e.g.
 foo._bar
 foo_.bar
 foo..bar
 foo__bar

 Are all these same ?
```

I prefer to add a flag to specify auto converting or not.

**Comment by struberg** [comment]
yes, you could not distinguish those in the EnvironmentConfigSource, but everywhere else. 
In practice it's not really an issue. 

We first catched this issue when integrating Docker where ENV=.. can also not contain any dots via scripts.

**Comment by kazumura** [comment]
I agree the auto converting as the default behavior.

But there are some people who already use '_' as the keys.
My point is, should we provide them an option to use this feature or not?
I don't know how many people already use '_'. May not major.

**Comment by TFaga** [comment]
+1 for `.` -> `_` as well. We're also doing this in KumuluzEE.

Another question though. How about other common characters that are used but not typically found or allowed in environemnt variable key names (like `-`, `[`, `]`, ...)? While there's not much that can be done about those examples, perhaps at least a note somewhere that certain characters may be problematic to use from the environment or that it's up to the implementation how it's additionally handled?

**Comment by Emily-Jiang** [comment]
Yes, I think we should just pick the commonly used one like "." for the reason of @kazumura brought up, which will create overlapping. We can clearly document this as you said@TFaga !

**Comment by lilian-benoit** [comment]
+1 for . -> _ as well.
Usually, we use _ for environment variable. 

is property name case-sensitive ? In fact, we have COM_ACME_ME as environment variable.

**Comment by OndrejM** [comment]
As I commented in https://github.com/eclipse/microprofile-config/issues/264#issuecomment-348296143:

I suggest to require that environment variables with underscores are mapped to multiple keys. It should be a problem if e.g. a variable `COM_ACME_ME` represents all of these keys:

- `COM_ACME_ME`
- `com_acme_me`
- `com.acme.me`

All of them with the same value. There's almost no chance that an application would want to distinguish between these keys and would expect that there are different values under those keys.

Other special characters llike [ or ] can be supported by reading the keys from variable values, e.g. for a config key `key[1]` there would be 2 env vars, one with `MP_CONFIG_KEY_` prefix and another one with `MP_CONFIG_VALUE_` prefix. `MP_CONFIG_KEY_STRANGE_KEY_1` would contain `key[1]` and `MP_CONFIG_VALUE_STRANGE_KEY_1` would contain the value. This could actually solve everything, even dotted keys.

**Comment by struberg** [comment]
Well, it's a fallback anyway. 
So I guess the ConfigSource will 
* first lookup case-sensitive (with dots)
* if not found -> lookup case-sensitive with '.'->'_'
* if still not found -> lookup uppercase with '.'->'_'

works for me.

Any implementation could provide another logic as well.
It could do more fallbacks, or have a custom mode to disable it. All good and fair.

**Comment by lilian-benoit** [comment]
+1 for this approach

**Comment by Emily-Jiang** [comment]
#49 closes this issue
