### ISSUE TITLE
Close Converters and ConfigSources which implement Closeable when shutting down

### ISSUE THREAD

**Issue by struberg** [eclipse/ConfigJSR#27]
this allows custom implementations to do a proper cleanup.

**Comment by lilian-benoit** [comment]
+1 , I understand use case for closing ConfigSources 
I don't see use cas for closing Converters. Have you an use case ?

**Comment by struberg** [comment]
preparing a PR right now

**Comment by struberg** [comment]
Pull Request sent. Plz review - txs!
