### ISSUE TITLE
Adding converter to the builder fails evaluating parametrized type with Lambda

### ISSUE THREAD

**Issue by atsticks** [eclipse/ConfigJSR#29]
Adding a Converter defined by a lamba expression fails:

```
ConfigBuilder b = ConfigProviderResolver.instance().getBuilder();
b.withConverters(val -> val);
```

Using an anonymous class works fine:

```
Converter<String> converter = new Converter<String>(){
            @Override
            public String convert(String value) {
                return value;
            }
        }; 
b.withConverters(converter);
```

SO we have probably to rework this part of the API. In Tamaya we therefore have things like:

`ConfigBuilder withConverters(Class type, Converter... converters);`

respectively

`<T> ConfigBuilder withConverters(TypeLiteral<T> type, Converter<T>... converters);`

Is this an issue, or how the target type can be evaluated?

**Comment by Emily-Jiang** [comment]
ConfigBuilder.withConverter(Class type, Converter converter)

**Comment by Emily-Jiang** [comment]
@atsticks can you take this on?
