### ISSUE TITLE
[TCK] add tests for converter's priority

### ISSUE THREAD

**Issue by jmesnil** [eclipse/ConfigJSR#36]
[Spec](https://github.com/eclipse/ConfigJSR/blob/master/spec/src/main/asciidoc/converters.asciidoc#adding-custom-converters) says:

> A custom Converter can define a priority with the @javax.annotation.Priority annotation. If a Priority annotation isn’t applied, a default priority of 100 is assumed. The Config will use the Converter with the highest Priority for each target type.

We need to add a test that add 2 converters (with different @Priority) for the same type and only the one with the highest priority is used.

**Comment by jmesnil** [comment]
covered by #37

**Comment by struberg** [comment]
resolved, closing now - thanks Jeff!
