### ISSUE TITLE
Merging guidence - at least on approval is needed

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/ConfigJSR#38]
In order to respect everyone's value, each PR must have an approval before it gets merged. I will investigate how to put this in github. In the meanwhile, please respect this rule. If you feel this should not be forced, please have your concerns aired out now.

**Comment by struberg** [comment]
You mean like #14 which got merged despite having an open unresolved review comment? ;)

Nah serious. I think we should not overcomplicate things. 
We MUST do a proper review before we finally ship the final JSR release.

But before that it's a balance between merging in immature ideas (should ofc not get merged) and having to many parallel changes open (which will slow us down and make it impossible to do any impl).

What happened in #13 _and_ #14 was that we (both btw) merged a PR to master which was not 100% finished, but the basic parts have been agreed on. For #14 it was a minor code fix, for #13 it's about whether to remove 3 bullets from the implicit converter criteria list. So we are effectively talking about removing (or not) 3 lines from our JavaDoc (and spec pdf).

Let's not make a biggie out of this, I think we can both live with whatever the EG finally votes for.

**Comment by Emily-Jiang** [comment]
I was commenting on #13. We were in the middle of discussion and you went ahead to merge it.
We should do review for each PR. In this way, we are not drifting off too much. A big -1 to what you have suggested. Please don't muddle the water. I don't know why you should brought up #14, since it was agreed to be merged during the meeting and said all issues are to be fixed under a separate commit since the design was agreed.
