### ISSUE TITLE
Create a ConfigJSR-tck github repo for the TCK

### ISSUE THREAD

**Issue by struberg** [eclipse/ConfigJSR#4]
Create a ConfigJSR-tck github repo for the TCK.
Has to be done by Eclipse.

**Comment by hendrikebbers** [comment]
Should be have several repos? Why not just using a Maven multi module project that contains API and TCK module? This will be much easier to stay always in sync.

**Comment by struberg** [comment]
Yes, that's how we did it in MP-config. 

The main point for starting a separate repo is to allow fixing bugs in the TCK (happens regularly) while not having to release the API + spec PDF which is in the same repo.

What we probably _could_ do:
1.) Have the same structure as in MP-config: api + spec (asciidoc) + tck.
2.) Once we published the Final spec + api we create a branch tck_mt where we remove the api and spec folders. So we have just the TCK in this branch and can do the maintenance from this branch without having to publish anything else.

**Comment by hendrikebbers** [comment]
Maybe it helps to deploy to bintray and than sync with Maven central (doing this for all my projects since some time).
Looks like the bintray deploy plugin has a skip-flag (see https://github.com/Devexperts/bintray-maven-plugin). By defining a profile it should be possible to deploy only the spec.

**Comment by struberg** [comment]
Skipping the deployment for certain modules is trivial.
I just prefer to have a reproducible tag without any superfluous parts.

Deploying to maven.central is also not a problem. 
Let's discuss the options on the next EG hangout.

**Comment by hendrikebbers** [comment]
@struberg issue can be closed.

**Comment by Emily-Jiang** [comment]
Has the tck repo been created, @struberg ?

**Comment by lilian-benoit** [comment]
I don't understand why this issue was closed. We separate repo between api/spec and tck ?
@Emily-Jiang you mention in minutes meeting that you follow up creation repo
New repo for tck don't have been created

**Comment by Emily-Jiang** [comment]
@lilian-benoit you were quite right. We still need to separate tck in a separate repo. I don't understand why @struberg closed this one.  have reopened this and will follow up on the repo creation. Hope to get the repo soon!

**Comment by struberg** [comment]
The separation of api/spec and TCK happened in most other EE projects becaues the TCK was fully closed source.
But there is absolutely no technical need to have the TCK in a separate GIT repo for ConfigJSR.

Even if we later ship bugfix releases of the TCK, then we can still simply just release the TCK without the api and spec projects from a git branch!
