### ISSUE TITLE
move Config#getValue to just provide String/String representation? 

### ISSUE THREAD

**Issue by struberg** [eclipse/ConfigJSR#64]
The original design of DeltaSpike was defering the Config to just String/String (key/value). 
Any typesafe behaviour and other features were built on top of the TypedResolver (our ConfigValue).
This is actually a much more consistent approach.

So should we remove anything beyond String/String from Config and defer to ConfigValue?
This would make our API much cleaner. 
The only real argument against this might be backward compatibility with MicroProfile-config.

**Comment by tomas-langer** [comment]
I think that this would add one more step when I need only to get a value.
now: config.getValue("key", Integer.class)
new: config.accessor("key").as(Integer.class).getValue()

My preference would be for the first, even when duplicating the code. Sometimes simplicity over "cleanness" is fine.

**Comment by struberg** [comment]
I think we can close this as we already came to a common understanding
