### ISSUE TITLE
Create a new method on Config to get ConfigAccessor

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/ConfigJSR#93]
We should add a method on Config to get a ConfigAccessor<T> instead of just getting String version

ConfigAccessor`<T>` access = config.access(String propName, T clazz)

As a consequence, the following method can be removed.
<N> ConfigAccessor<N> as(Class<N> clazz);

**Comment by struberg** [comment]
As already explained in the EG meeting I think we do not need this.
The functionality is already covered via `config.access("my.server.port").as(Integer.class)....;`
So this method is essentially duplicating existing functionality.
